flask_project_structure/blueprint_template/blueprint_template.py
import pandas as pd
from flask import Blueprint, render_template, request, session
from modulos import config_inicial as ci
from funciones import funciones_generales as f

example_bp = Blueprint('example_bp'
,__name__,template_folder = 'templates'
)

@example_bp.route('/dropdown',methods=['POST','GET'])
def dropdown():
    try:
        # we create a list to be used as a checklist
        dropdown_list = ['option1','option2','option3']
        # re-directing to another place in the 
        return render_template('blueprint_template/dropdown.html', opciones = dropdown_list)
    except Exception as e:
        response_message = f'error when rendering the dropdown {e}'
        ci.logger.debug(response_message)
        return render_template('response.html',response_message = response_message)

@example_bp.route('/dropdown_response',methods=['POST','GET'])
def dropdown_response():
    try: 
        opcion_seleccionada = request.form['seleccion']
        print('ok')
    except Exception as e:
        response_message = f'error when obtaining the selected option {e}'
        ci.logger.debug(response_message)
        return render_template('response.html',response_message = response_message)

@example_bp.route('/checked_checklist',methods=['POST','GET'])
def checked_checklist():
    try: 
        # we create a list to be used as a checklist
        checklist_input = ['option1','option2','option3','option4','option5']
        # we create another list to define the checked options
        checked_checklist_input = ['option2','option3']
        # we render the template
        return render_template('blueprint_template/checked_checklist.html', checklist = checklist_input, checked_checklist = checked_checklist_input)
    
    except Exception as e:
        response_message = f'error when rendering checked_checklist {e}'
        ci.logger.debug(response_message)
        return render_template('response.html',response_message = response_message)    

@example_bp.route('/checked_checklist_response',methods=['POST','GET'])
def checked_checklist_response():
    try:
        selected_options = request.form.getlist('options[]')
        print('ok')
        # re-direction example here 
        message = 'Redirigiendo a checked_checklist...'
        url = 'example_bp.checked_checklist'
        return render_template('blueprint_template/redireccion.html',message = message, url = url) 
    except Exception as e:
        response_message = f'error when obtaining the selected options from the checklist {e}'
        ci.logger.debug(response_message)
        return render_template('response.html',response_message = response_message)

@example_bp.route('/form',methods=['POST','GET'])
def form():
    try:
        # we create a list to be used as a checklist
        checklist_input = ['option1','option2','option3','option4','option5']
        # we create another list to define the checked options
        checked_checklist_input = ['option2','option3']
        # re-directing to another place in the 
        return render_template('blueprint_template/form.html', checklist = checklist_input, checked_checklist = checked_checklist_input)
    except Exception as e:
        response_message = f'error when rendering the dropdown {e}'
        ci.logger.debug(response_message)
        return render_template('response.html',response_message = response_message)

@example_bp.route('/form_response',methods=['POST','GET'])
def form_response():
    try:
        selected_options = request.form.getlist('options[]')
        form1_text = request.form['form1']
        form2_text = request.form['form2']
        print('ok')
        # re-direction example here 
        message = 'Redirigiendo a checked_checklist...'
        url = 'example_bp.checked_checklist'
        return render_template('blueprint_template/redireccion.html',message = message, url = url) 
    except Exception as e:
        response_message = f'error when obtaining the selected options from the checklist {e}'
        ci.logger.debug(response_message)
        return render_template('response.html',response_message = response_message)

flask_project_structure/blueprint_template/templates/blueprint_template/checked_checklist.html
{% extends "response_base.html" %}

{% block content %}

<h2>Selecciona los checklist a procesar</h2>
<br>
<div class="formulario"></div>
<form action="{{ url_for('example_bp.checked_checklist_response') }}" method="post">
  <fieldset>
  <input type="hidden" id="id" name="id" value="{{ operario }}" readonly >
    <br>
    {% for item in checklist %}
      {% if item in checked_checklist %}
        <label for="{{ options }}">
          <input type="checkbox" id="{{ options }}" name="options[]" value="{{ item }}" checked>
          {{ item }}
        </label>
      {% else %}
        <label for="{{ options }}">
          <input type="checkbox" id="{{ options }}" name="options[]" value="{{ item }}"> 
          {{ item }} 
        </label>
      {% endif %}
    <br>
    {% endfor %}
  </fieldset>
  <button type="submit">Enviar</button>
</form>
{% endblock %}

flask_project_structure/blueprint_template/templates/blueprint_template/dropdown.html
{% extends "response_base.html" %}

{% block content %}

<form action="{{ url_for('example_bp.dropdown_response') }}" method="post">
<h2 align="center">Choose the option</h2><br />
<select name="seleccion" id="seleccion" class="form-control">
<option value="">Select Option</option>';
{% for opcion in opciones %}
<option value="{{opcion}}">{{opcion}}</option>';    
{% endfor %}
</select>
<input type="submit" name="Seleccionar Opcion"/>
</form>
{% endblock %}

flask_project_structure/blueprint_template/templates/blueprint_template/form.html
{% extends "response_base.html" %}

{% block content %}

<div class="formulario"></div>
<form action="{{ url_for('example_bp.form_response') }}" method="post">

    <textarea id="form1" name="form1" rows="2" cols="100" maxlength="1000" 
	placeholder = "Placedholder for form1" 
	required></textarea><br>

	<textarea id="form2" name="form2" rows="10" cols="100" maxlength="2000" 
	placeholder = "Placedholder for form2"		
 	required></textarea><br>

    
     {% for item in checklist %}
     {% if item in checked_checklist %}
       <label for="{{ options }}">
         <input type="checkbox" id="{{ options }}" name="options[]" value="{{ item }}" checked>
         {{ item }}
       </label>
     {% else %}
       <label for="{{ options }}">
         <input type="checkbox" id="{{ options }}" name="options[]" value="{{ item }}"> 
         {{ item }} 
       </label>
     {% endif %}
   <br>
   {% endfor %}
	
	<input type="submit" value="Submit">
	</form>
{% endblock %}

flask_project_structure/blueprint_template/templates/blueprint_template/reading_table.html
{% extends "response_base.html" %}

{% block content %}

<div class="formulario"></div>
<form action="{{ url_for('QR_bp.getQR') }}" method="post">
    <!-- Add the dynamic dropdown list here -->
    <label for="seleccionpuesto">Escoge un puesto:</label>
    <select id="seleccionpuesto" name="seleccionpuesto" required>
        {% if initial_selection %}
            <option value="{{initial_selection}}" selected>{{initial_selection}}</option>
        {% else %}
            <option value="" disabled selected>Escoge un puesto</option>    
        {% endif %}    
        {% for puesto in lista_puestos %}
            <option value="{{ puesto }}">{{ puesto }}</option>
        {% endfor %}
    </select><br>

    <textarea id="QR" name="QR" rows="2" cols="100" maxlength="1000" autofocus onfocus="this.select()" onkeydown="if(event.keyCode==13){event.preventDefault();document.getElementById('submit').click();}"
	placeholder = "Haz click aquí y lee el código QR" 
	required></textarea><br>
	<br>
	<input type="submit" id = "submit" value="Leer QR">
	</form>
    <br><br>
    
{% if initial_selection %}
<div class="table-responsive" contentEditable="True" id="editable-table">
{{ table_html | safe }}
</div>
<button id="submit-button">Cargar tabla</button>
    
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
<script>
    $(document).ready(function() {
      // Make all header cells not editable
      $('#editable-table th').attr('contentEditable', 'false');  
      
      // Make all cells not editable
      $('#editable-table td').not(':nth-child(8)').attr('contentEditable', 'false');
    
      // Make cells in column 3 editable
      $('#editable-table td:nth-child(8)').attr('contentEditable', 'true');
    });
</script>
    
<script>
$(document).ready(function() {
    $('#submit-button').click(function() {
    
        var edited_table_html = $('#editable-table').html();
          
        $.ajax({
            type: 'POST',
            url: '/modificarlecturas_response',
            data: {edited_table_html: edited_table_html},
            success:function(response){ document.write(response); }
        });
    });
});
</script>
<br>
{% endif %} 
<br>
{% endblock %}

flask_project_structure/blueprint_template/templates/blueprint_template/redireccion.html
{% extends "response_base.html" %}

{% block content %}
<form name = "myform" action="{{ url_for(url) }}" method="post">
<h2 align="center">{{message}}</h2>
</form>

<script type="text/javascript">
    setTimeout(function(){
        document.myform.submit();
    }, 2000); // 10000 milliseconds = 10 seconds
</script>

{% endblock %}